from engine.importlib import *


ANIMATEURID = 725737781485109259
EVENTPLAYERID = 725737796001595473
EVENTSCHANNELID = 725737847277092986
WHITELIST = [ANIMATEURID]

DATA_PATH = "events.json"
DEFAULT_DATA = {"events":[]}

VALID_EMOJI = '✅'
FAIL_EMOJI = '❎'
COMMAND_VALID_EMOJI = '✅'
COMMAND_FAIL_EMOJI = '❌'

TIME_ZONE = 'Europe/Paris'
LOCAL_TZ = pytz.timezone(TIME_ZONE)
TIME_SEPARATOR = ':'
DATE_SEPARATOR = '-'
TD_SEPARATOR = ' '
DATE_FORMAT = '%d'+DATE_SEPARATOR+'%m'+DATE_SEPARATOR+'%y'+ TD_SEPARATOR+'%H'+TIME_SEPARATOR+'%M'
